### ISSUE TITLE
Missing Translation "Tend to Fields" in other languages

### ISSUE THREAD

**Issue by Mickey103** [Ponzel/FoundersFortuneLocalization#86]
Hi Daniel, 

Could you check the following: I have for dutch 100% completed the translations, but when I play a game in dutch, I still get an English text, When search for that sentense in the Localization files I do see multple Translation. 
Could it be that for this the multiple languages are not assigned to display?

![tend to fields no other Translations](https://user-images.githubusercontent.com/77390728/106369281-56385d00-6350-11eb-8d67-77e8a2359e70.jpg)

**Comment by Ponzel** [comment]
Sorry for putting it off for so long, just had a look and couldn't reproduce it.
Seems like this should be the "geef water" interaction? was the translation string just wrong maybe?

**Comment by Mickey103** [comment]
Thx for your reply, but I do not agree with that. The action stated in English is the "Tend to fields" action . The NL translation is as I have pasted into the image "Verzorg de velden". I do not see that it has someting to do with the section "Water Plant" as that is the "Geef water" interaction. The "tend to fields" sentence will only appear in the JSON files in Professions,json and is thus not coming from the interactions.json. Maybe this is then wrongly coded in the game perhaps?

**Comment by Ponzel** [comment]
The thing is: The game doesn't contain a "Tend to fields" interaction. The text in the screenshot you've posted is about the profession specialization menu. So that's why I'm hesitant believing that the game takes text from the wrong location.

Also, I'm not sure how you're getting this issue unless you have a local translation folder with different translations active.
This is what I see when I play the default game in Dutch:

![image](https://user-images.githubusercontent.com/8333811/114061714-05d10480-9897-11eb-8143-f5a07c3d120f.png)

Let me know if any of these translations are wrong or if I misunderstood something.

**Comment by Mickey103** [comment]
Thx you for this explaination, I was also searching and I finally found the issue, 
which was totally on my side. I was using a Mod  which also using a Localization file only for English 

Sorry for the confusion I might cause.
